# Generated by Django 3.2.7 on 2021-09-21 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('targets', models.CharField(choices=[('individual', 'INDIVIDUAL'), ('all', 'ALL STUDENTS'), ('eights', 'GRADE 8'), ('nines', 'GRADE 9'), ('tens', 'GRADE 10'), ('elvens', 'GRADE 11'), ('twelves', 'GRADE 12'), ('other', 'OTHER')], max_length=200)),
                ('type', models.CharField(choices=[('once', 'ONCE-OFF'), ('often', 'OFTEN')], max_length=200)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(default=None, max_length=255, null=True)),
                ('draft', models.BooleanField(blank=True, default=False)),
                ('due', models.DateField(default=datetime.date.today)),
                ('date', models.DateField(default=datetime.date.today)),
                ('terms', models.CharField(blank=True, max_length=128)),
                ('comments', models.TextField(blank=True)),
                ('is_voided', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('reference_number', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('date', models.DateField(auto_now_add=True)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer'), ('debit card', 'Debit Card'), ('mobile', 'Mobile-Transfer')], default='transfer', max_length=32)),
                ('reference_number', models.CharField(default=None, max_length=255, null=True)),
                ('comments', models.TextField(default='Thank you for your business')),
            ],
        ),
    ]
