# Generated by Django 3.2.7 on 2021-09-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='draft',
        ),
        migrations.AlterField(
            model_name='fee',
            name='targets',
            field=models.CharField(choices=[('individual', 'INDIVIDUAL'), ('all', 'ALL STUDENTS'), ('one', 'FORM 1'), ('two', 'FORM 2'), ('three', 'FORM 3'), ('four', 'FORM 4'), ('five', 'FORM 5'), ('six', 'FORM 6'), ('other', 'OTHER')], max_length=200),
        ),
    ]
