# Generated by Django 3.2.7 on 2021-09-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_auto_20210922_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='comments',
            field=models.TextField(blank=True, default='Make sure you pay your fees as soon as possible'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='terms',
            field=models.CharField(blank=True, default='Pay soon', max_length=128),
        ),
    ]
