# Generated by Django 3.2.7 on 2021-09-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_auto_20210922_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
