# Generated by Django 3.2.7 on 2021-09-22 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_alter_invoiceline_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceline',
            name='discount',
        ),
    ]
