export const GET_APPROVED_BOOK_REVIEWS_START = 'GET_APPROVED_BOOK_REVIEWS_START';
export const GET_APPROVED_BOOK_REVIEWS_SUCCESS = 'GET_APPROVED_BOOK_REVIEWS_SUCCESS';
export const GET_APPROVED_BOOK_REVIEWS_FAIL = 'GET_APPROVED_BOOK_REVIEWS_FAIL';
export const GET_APPROVED_BOOK_REVIEW_START = 'GET_APPROVED_BOOK_REVIEW_START';
export const GET_APPROVED_BOOK_REVIEW_SUCCESS = 'GET_APPROVED_BOOK_REVIEW_SUCCESS';
export const GET_APPROVED_BOOK_REVIEW_FAIL = 'GET_APPROVED_BOOK_REVIEW_FAIL';