export const GET_ASSETS_START = 'GET_ASSETS_START';
export const GET_ASSETS_SUCCESS = 'GET_ASSETS_SUCCESS';
export const GET_ASSETS_FAIL = 'GET_ASSETS_FAIL';
export const CREATE_ASSET_START = 'CREATE_ASSET_START';
export const CREATE_ASSET_SUCCESS = 'CREATE_ASSET_SUCCESS';
export const CREATE_ASSET_FAIL = 'CREATE_ASSET_FAIL';
export const GET_ASSET_START = 'GET_ASSET_START';
export const GET_ASSET_SUCCESS = 'GET_ASSET_SUCCESS';
export const GET_ASSET_FAIL = 'GET_ASSET_FAIL';
export const EDIT_ASSET = 'EDIT_ASSET';

export const GET_DELETED_ASSETS_START = 'GET_DELETED_ASSETS_START';
export const GET_DELETED_ASSETS_SUCCESS = 'GET_DELETED_ASSETS_SUCCESS';
export const GET_DELETED_ASSETS_FAIL = 'GET_DELETED_ASSETS_FAIL';
export const GET_VERIFIED_ASSETS_SUCCESS = 'GET_VERIFIED_ASSETS_SUCCESS';
export const GET_VERIFIED_ASSETS_FAIL = 'GET_VERIFIED_ASSETS_FAIL';
export const GET_VERIFIED_ASSET_START = 'GET_VERIFIED_ASSET_START';
export const GET_VERIFIED_ASSET_SUCCESS = 'GET_VERIFIED_ASSET_SUCCESS';
export const GET_VERIFIED_ASSET_FAIL = 'GET_VERIFIED_ASSET_FAIL';
export const GET_VERIFIED_ASSETS_START = 'GET_VERIFIED_ASSETS_START';
export const GET_UNVERIFIED_ASSETS_START = 'GET_UNVERIFIED_ASSETS_START';
export const GET_UNVERIFIED_ASSETS_SUCCESS = 'GET_UNVERIFIED_ASSETS_SUCCESS';
export const GET_UNVERIFIED_ASSETS_FAIL = 'GET_UNVERIFIED_ASSETS_FAIL';
export const CREATE_UNVERIFIED_ASSET_START = 'CREATE_UNVERIFIED_ASSET_START';
export const CREATE_UNVERIFIED_ASSET_SUCCESS = 'CREATE_UNVERIFIED_ASSET_SUCCESS';
export const CREATE_UNVERIFIED_ASSET_FAIL = 'CREATE_UNVERIFIED_ASSET_FAIL';
export const GET_UNVERIFIED_ASSET_START = 'GET_UNVERIFIED_ASSET_START';
export const GET_UNVERIFIED_ASSET_SUCCESS = 'GET_UNVERIFIED_ASSET_SUCCESS';
export const GET_UNVERIFIED_ASSET_FAIL = 'GET_UNVERIFIED_ASSET_FAIL';
export const EDIT_UNVERIFIED_ASSET = 'EDIT_UNVERIFIED_ASSET';

export const VERIFY_ASSET_SUCCESS = 'VERIFY_ASSET_SUCCESS';
export const VERIFY_ASSET_FAIL = 'VERIFY_ASSET_FAIL';
export const VERIFY_ASSET_START = 'VERIFY_ASSET_START';
export const DELETE_ASSET_SUCCESS = 'DELETE_ASSET_SUCCESS';
export const DELETE_ASSET_FAIL = 'DELETE_ASSET_FAIL';
export const DELETE_ASSET_START = 'DELETE_ASSET_START';

