export const GET_CUSTOMERS_START = 'GET_CUSTOMERS_START';
export const GET_CUSTOMERS_SUCCESS = 'GET_CUSTOMERS_SUCCESS';
export const GET_CUSTOMERS_FAIL = 'GET_CUSTOMERS_FAIL';
export const CREATE_CUSTOMER_START = 'CREATE_CUSTOMER_START';
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS';
export const CREATE_CUSTOMER_FAIL = 'CREATE_CUSTOMER_FAIL';
export const GET_CUSTOMER_START = 'GET_CUSTOMER_START';
export const GET_CUSTOMER_SUCCESS = 'GET_CUSTOMER_SUCCESS';
export const GET_CUSTOMER_FAIL = 'GET_CUSTOMER_FAIL';
export const EDIT_CUSTOMER = 'EDIT_CUSTOMER';

export const GET_CUSTOMER_UNPAID_INVOICES_START = 'GET_CUSTOMER_UNPAID_INVOICES_START';
export const GET_CUSTOMER_UNPAID_INVOICES_SUCCESS = 'GET_CUSTOMER_UNPAID_INVOICES_SUCCESS';
export const GET_CUSTOMER_UNPAID_INVOICES_FAIL = 'GET_CUSTOMER_UNPAID_INVOICES_FAIL';
export const GET_CUSTOMER_UNPAID_INVOICE_START = 'GET_CUSTOMER_UNPAID_INVOICE_START';
export const GET_CUSTOMER_UNPAID_INVOICE_SUCCESS = 'GET_CUSTOMER_UNPAID_INVOICE_SUCCESS';
export const GET_CUSTOMER_UNPAID_INVOICE_FAIL = 'GET_CUSTOMER_UNPAID_INVOICE_FAIL';
export const GET_CUSTOMER_EBOOK_ORDER_ITEMS_START = 'GET_CUSTOMER_EBOOK_ORDER_ITEMS_START';
export const GET_CUSTOMER_EBOOK_ORDER_ITEMS_SUCCESS = 'GET_CUSTOMER_EBOOK_ORDER_ITEMS_SUCCESS';
export const GET_CUSTOMER_EBOOK_ORDER_ITEMS_FAIL = 'GET_CUSTOMER_EBOOK_ORDER_ITEMS_FAIL';
export const GET_CUSTOMER_EBOOK_ORDER_ITEM_START = 'GET_CUSTOMER_EBOOK_ORDER_ITEM_START';
export const GET_CUSTOMER_EBOOK_ORDER_ITEM_SUCCESS = 'GET_CUSTOMER_EBOOK_ORDER_ITEM_SUCCESS';
export const GET_CUSTOMER_EBOOK_ORDER_ITEM_FAIL = 'GET_CUSTOMER_EBOOK_ORDER_ITEM_FAIL';
export const GET_CUSTOMER_HARDCOPY_ORDER_ITEMS_START = 'GET_CUSTOMER_HARDCOPY_ORDER_ITEMS_START';
export const GET_CUSTOMER_HARDCOPY_ORDER_ITEMS_SUCCESS = 'GET_CUSTOMER_HARDCOPY_ORDER_ITEMS_SUCCESS';
export const GET_CUSTOMER_HARDCOPY_ORDER_ITEMS_FAIL = 'GET_CUSTOMER_HARDCOPY_ORDER_ITEMS_FAIL';
export const GET_CUSTOMER_HARDCOPY_ORDER_ITEM_START = 'GET_CUSTOMER_HARDCOPY_ORDER_ITEM_START';
export const GET_CUSTOMER_HARDCOPY_ORDER_ITEM_SUCCESS = 'GET_CUSTOMER_HARDCOPY_ORDER_ITEM_SUCCESS';
export const GET_CUSTOMER_HARDCOPY_ORDER_ITEM_FAIL = 'GET_CUSTOMER_HARDCOPY_ORDER_ITEM_FAIL';
export const GET_CUSTOMER_PARTIALY_PAID_INVOICES_START = 'GET_CUSTOMER_PARTIALY_PAID_INVOICES_START';
export const GET_CUSTOMER_PARTIALY_PAID_INVOICES_SUCCESS = 'GET_CUSTOMER_PARTIALY_PAID_INVOICES_SUCCESS';
export const GET_CUSTOMER_PARTIALY_PAID_INVOICES_FAIL = 'GET_CUSTOMER_PARTIALY_PAID_INVOICES_FAIL';
export const GET_CUSTOMER_PARTIALY_PAID_INVOICE_START = 'GET_CUSTOMER_PARTIALY_PAID_INVOICE_START';
export const GET_CUSTOMER_PARTIALY_PAID_INVOICE_SUCCESS = 'GET_CUSTOMER_PARTIALY_PAID_INVOICE_SUCCESS';
export const GET_CUSTOMER_PARTIALY_PAID_INVOICE_FAIL = 'GET_CUSTOMER_PARTIALY_PAID_INVOICE_FAIL';
export const GET_CUSTOMER_SERIES_ORDER_ITEMS_START = 'GET_CUSTOMER_SERIES_ORDER_ITEMS_START';
export const GET_CUSTOMER_SERIES_ORDER_ITEMS_SUCCESS = 'GET_CUSTOMER_SERIES_ORDER_ITEMS_SUCCESS';
export const GET_CUSTOMER_SERIES_ORDER_ITEMS_FAIL = 'GET_CUSTOMER_SERIES_ORDER_ITEMS_FAIL';
export const GET_CUSTOMER_SERIES_ORDER_ITEM_START = 'GET_CUSTOMER_SERIES_ORDER_ITEM_START';
export const GET_CUSTOMER_SERIES_ORDER_ITEM_SUCCESS = 'GET_CUSTOMER_SERIES_ORDER_ITEM_SUCCESS';
export const GET_CUSTOMER_SERIES_ORDER_ITEM_FAIL = 'GET_CUSTOMER_SERIES_ORDER_ITEM_FAIL';
export const GET_CUSTOMER_FULLY_PAID_INVOICES_START = 'GET_CUSTOMER_FULLY_PAID_INVOICES_START';
export const GET_CUSTOMER_FULLY_PAID_INVOICES_SUCCESS = 'GET_CUSTOMER_FULLY_PAID_INVOICES_SUCCESS';
export const GET_CUSTOMER_FULLY_PAID_INVOICES_FAIL = 'GET_CUSTOMER_FULLY_PAID_INVOICES_FAIL';
export const GET_CUSTOMER_FULLY_PAID_INVOICE_START = 'GET_CUSTOMER_FULLY_PAID_INVOICE_START';
export const GET_CUSTOMER_FULLY_PAID_INVOICE_SUCCESS = 'GET_CUSTOMER_FULLY_PAID_INVOICE_SUCCESS';
export const GET_CUSTOMER_FULLY_PAID_INVOICE_FAIL = 'GET_CUSTOMER_FULLY_PAID_INVOICE_FAIL';

export const CREATE_EBOOK_CUSTOMER_ORDER_ITEM_START = 'CREATE_EBOOK_CUSTOMER_ORDER_ITEM_START';
export const CREATE_EBOOK_CUSTOMER_ORDER_ITEM_SUCCESS = 'CREATE_EBOOK_CUSTOMER_ORDER_ITEM_SUCCESS';
export const CREATE_EBOOK_CUSTOMER_ORDER_ITEM_FAIL = 'CREATE_EBOOK_CUSTOMER_ORDER_ITEM_FAIL';
export const CREATE_HARDCOPY_CUSTOMER_ORDER_ITEM_START = 'CREATE_HARDCOPY_CUSTOMER_ORDER_ITEM_START';
export const CREATE_HARDCOPY_CUSTOMER_ORDER_ITEM_SUCCESS = 'CREATE_HARDCOPY_CUSTOMER_ORDER_ITEM_SUCCESS';
export const CREATE_HARDCOPY_CUSTOMER_ORDER_ITEM_FAIL = 'CREATE_HARDCOPY_CUSTOMER_ORDER_ITEM_FAIL';
export const CREATE_SERIES_CUSTOMER_ORDER_ITEM_START = 'CREATE_SERIES_CUSTOMER_ORDER_ITEM_START';
export const CREATE_SERIES_CUSTOMER_ORDER_ITEM_SUCCESS = 'CREATE_SERIES_CUSTOMER_ORDER_ITEM_SUCCESS';
export const CREATE_SERIES_CUSTOMER_ORDER_ITEM_FAIL = 'CREATE_SERIES_CUSTOMER_ORDER_ITEM_FAIL';


export const GET_CUSTOMER_CART_START = 'GET_CUSTOMER_CART_START';
export const GET_CUSTOMER_CART_SUCCESS = 'GET_CUSTOMER_CART_SUCCESS';
export const GET_CUSTOMER_CART_FAIL = 'GET_CUSTOMER_CART_FAIL';

export const GET_CUSTOMER_PAYMENTS_START = 'GET_CUSTOMER_PAYMENTS_START';
export const GET_CUSTOMER_PAYMENTS_SUCCESS = 'GET_CUSTOMER_PAYMENTS_SUCCESS';
export const GET_CUSTOMER_PAYMENTS_FAIL = 'GET_CUSTOMER_PAYMENTS_FAIL';


