export const GET_EXPIRED_ADVERTS_START = 'GET_EXPIRED_ADVERTS_START';
export const GET_EXPIRED_ADVERTS_SUCCESS = 'GET_EXPIRED_ADVERTS_SUCCESS';
export const GET_EXPIRED_ADVERTS_FAIL = 'GET_EXPIRED_ADVERTS_FAIL';
export const GET_EXPIRED_ADVERT_START = 'GET_EXPIRED_ADVERT_START';
export const GET_EXPIRED_ADVERT_SUCCESS = 'GET_EXPIRED_ADVERT_SUCCESS';
export const GET_EXPIRED_ADVERT_FAIL = 'GET_EXPIRED_ADVERT_FAIL';