export const GET_JOURNAL_ENTRIES_START = 'GET_JOURNAL_ENTRIES_START';
export const GET_JOURNAL_ENTRIES_SUCCESS = 'GET_JOURNAL_ENTRIES_SUCCESS';
export const GET_JOURNAL_ENTRIES_FAIL = 'GET_JOURNAL_ENTRIES_FAIL';
