export const GET_ONCE_OFFS_START = 'GET_ONCE_OFFS_START';
export const GET_ONCE_OFFS_SUCCESS = 'GET_ONCE_OFFS_SUCCESS';
export const GET_ONCE_OFFS_FAIL = 'GET_ONCE_OFFS_FAIL';
export const CREATE_ONCE_OFF_START = 'CREATE_ONCE_OFF_START';
export const CREATE_ONCE_OFF_SUCCESS = 'CREATE_ONCE_OFF_SUCCESS';
export const CREATE_ONCE_OFF_FAIL = 'CREATE_ONCE_OFF_FAIL';
export const GET_ONCE_OFF_START = 'GET_ONCE_OFF_START';
export const GET_ONCE_OFF_SUCCESS = 'GET_ONCE_OFF_SUCCESS';
export const GET_ONCE_OFF_FAIL = 'GET_ONCE_OFF_FAIL';
export const EDIT_ONCE_OFF = 'EDIT_ONCE_OFF';
export const GET_HARD_COPY_IMAGES_START = 'GET_HARD_COPY_IMAGES_START';
export const GET_HARD_COPY_IMAGES_SUCCESS = 'GET_HARD_COPY_IMAGES_SUCCESS';
export const GET_HARD_COPY_IMAGES_FAIL = 'GET_HARD_COPY_IMAGES_FAIL';

export const CREATE_HARD_COPY_IMAGE_START = 'CREATE_HARD_COPY_IMAGE_START';
export const CREATE_HARD_COPY_IMAGE_SUCCESS = 'CREATE_HARD_COPY_IMAGE_SUCCESS';
export const CREATE_HARD_COPY_IMAGE_FAIL = 'CREATE_HARD_COPY_IMAGE_FAIL';

export const CREATE_HARD_COPY_COVER_START = 'CREATE_HARD_COPY_COVER_START';
export const CREATE_HARD_COPY_COVER_SUCCESS = 'CREATE_HARD_COPY_COVER_SUCCESS';
export const CREATE_HARD_COPY_COVER_FAIL = 'CREATE_HARD_COPY_COVER_FAIL';


export const UNLOCK_HARDCOPY_START = 'UNLOCK_HARDCOPY_START';
export const UNLOCK_HARDCOPY_SUCCESS = 'UNLOCK_HARDCOPY_SUCCESS';
export const UNLOCK_HARDCOPY_FAIL = 'UNLOCK_HARDCOPY_FAIL';
