export const GET_ONGOING_ADVERTS_START = 'GET_ONGOING_ADVERTS_START';
export const GET_ONGOING_ADVERTS_SUCCESS = 'GET_ONGOING_ADVERTS_SUCCESS';
export const GET_ONGOING_ADVERTS_FAIL = 'GET_ONGOING_ADVERTS_FAIL';
export const GET_ONGOING_ADVERT_START = 'GET_ONGOING_ADVERT_START';
export const GET_ONGOING_ADVERT_SUCCESS = 'GET_ONGOING_ADVERT_SUCCESS';
export const GET_ONGOING_ADVERT_FAIL = 'GET_ONGOING_ADVERT_FAIL';