export const GET_FULLY_PAID_ORDERS_START = 'GET_FULLY_PAID_ORDERS_START';
export const GET_FULLY_PAID_ORDERS_SUCCESS = 'GET_FULLY_PAID_ORDERS_SUCCESS';
export const GET_FULLY_PAID_ORDERS_FAIL = 'GET_FULLY_PAID_ORDERS_FAIL';
export const GET_FULLY_PAID_ORDER_START = 'GET_FULLY_PAID_ORDER_START';
export const GET_FULLY_PAID_ORDER_SUCCESS = 'GET_FULLY_PAID_ORDER_SUCCESS';
export const GET_FULLY_PAID_ORDER_FAIL = 'GET_FULLY_PAID_ORDER_FAIL';
export const GET_PARTIALLY_PAID_ORDERS_START = 'GET_PARTIALLY_PAID_ORDERS_START';
export const GET_PARTIALLY_PAID_ORDERS_SUCCESS = 'GET_PARTIALLY_PAID_ORDERS_SUCCESS';
export const GET_PARTIALLY_PAID_ORDERS_FAIL = 'GET_PARTIALLY_PAID_ORDERS_FAIL';
export const GET_PARTIALLY_PAID_ORDER_START = 'GET_PARTIALLY_PAID_ORDER_START';
export const GET_PARTIALLY_PAID_ORDER_SUCCESS = 'GET_PARTIALLY_PAID_ORDER_SUCCESS';
export const GET_PARTIALLY_PAID_ORDER_FAIL = 'GET_PARTIALLY_PAID_ORDER_FAIL';
export const GET_UNPAID_ORDERS_START = 'GET_UNPAID_ORDERS_START';
export const GET_UNPAID_ORDERS_SUCCESS = 'GET_UNPAID_ORDERS_SUCCESS';
export const GET_UNPAID_ORDERS_FAIL = 'GET_UNPAID_ORDERS_FAIL';
export const GET_UNPAID_ORDER_START = 'GET_UNPAID_ORDER_START';
export const GET_UNPAID_ORDER_SUCCESS = 'GET_UNPAID_ORDER_SUCCESS';
export const GET_UNPAID_ORDER_FAIL = 'GET_UNPAID_ORDER_FAIL';
export const GET_UNVERIFIED_ORDERS_START = 'GET_UNVERIFIED_ORDERS_START';
export const GET_UNVERIFIED_ORDERS_SUCCESS = 'GET_UNVERIFIED_ORDERS_SUCCESS';
export const GET_UNVERIFIED_ORDERS_FAIL = 'GET_UNVERIFIED_ORDERS_FAIL';
export const GET_UNVERIFIED_ORDER_START = 'GET_UNVERIFIED_ORDER_START';
export const GET_UNVERIFIED_ORDER_SUCCESS = 'GET_UNVERIFIED_ORDER_SUCCESS';
export const GET_UNVERIFIED_ORDER_FAIL = 'GET_UNVERIFIED_ORDER_FAIL';
export const GET_FULLY_RECEIVED_ORDERS_START = 'GET_FULLY_RECEIVED_ORDERS_START';
export const GET_FULLY_RECEIVED_ORDERS_SUCCESS = 'GET_FULLY_RECEIVED_ORDERS_SUCCESS';
export const GET_FULLY_RECEIVED_ORDERS_FAIL = 'GET_FULLY_RECEIVED_ORDERS_FAIL';
export const GET_FULLY_RECEIVED_ORDER_START = 'GET_FULLY_RECEIVED_ORDER_START';
export const GET_FULLY_RECEIVED_ORDER_SUCCESS = 'GET_FULLY_RECEIVED_ORDER_SUCCESS';
export const GET_FULLY_RECEIVED_ORDER_FAIL = 'GET_FULLY_RECEIVED_ORDER_FAIL';
export const GET_PARTIALLY_RECEIVED_ORDERS_START = 'GET_PARTIALLY_RECEIVED_ORDERS_START';
export const GET_PARTIALLY_RECEIVED_ORDERS_SUCCESS = 'GET_PARTIALLY_RECEIVED_ORDERS_SUCCESS';
export const GET_PARTIALLY_RECEIVED_ORDERS_FAIL = 'GET_PARTIALLY_RECEIVED_ORDERS_FAIL';
export const GET_PARTIALLY_RECEIVED_ORDER_START = 'GET_PARTIALLY_RECEIVED_ORDER_START';
export const GET_PARTIALLY_RECEIVED_ORDER_SUCCESS = 'GET_PARTIALLY_RECEIVED_ORDER_SUCCESS';
export const GET_PARTIALLY_RECEIVED_ORDER_FAIL = 'GET_PARTIALLY_RECEIVED_ORDER_FAIL';
export const GET_UNRECEIVED_ORDERS_START = 'GET_UNRECEIVED_ORDERS_START';
export const GET_UNRECEIVED_ORDERS_SUCCESS = 'GET_UNRECEIVED_ORDERS_SUCCESS';
export const GET_UNRECEIVED_ORDERS_FAIL = 'GET_UNRECEIVED_ORDERS_FAIL';
export const GET_UNRECEIVED_ORDER_START = 'GET_UNRECEIVED_ORDER_START';
export const GET_UNRECEIVED_ORDER_SUCCESS = 'GET_UNRECEIVED_ORDER_SUCCESS';
export const GET_UNRECEIVED_ORDER_FAIL = 'GET_UNRECEIVED_ORDER_FAIL';
export const GET_UNVERIFIED_DEBIT_NOTES_START = 'GET_UNVERIFIED_DEBIT_NOTES_START';
export const GET_UNVERIFIED_DEBIT_NOTES_SUCCESS = 'GET_UNVERIFIED_DEBIT_NOTES_SUCCESS';
export const GET_UNVERIFIED_DEBIT_NOTES_FAIL = 'GET_UNVERIFIED_DEBIT_NOTES_FAIL';
export const GET_UNVERIFIED_DEBIT_NOTE_START = 'GET_UNVERIFIED_DEBIT_NOTE_START';
export const GET_UNVERIFIED_DEBIT_NOTE_SUCCESS = 'GET_UNVERIFIED_DEBIT_NOTE_SUCCESS';
export const GET_UNVERIFIED_DEBIT_NOTE_FAIL = 'GET_UNVERIFIED_DEBIT_NOTE_FAIL';
export const GET_VERIFIED_DEBIT_NOTES_START = 'GET_VERIFIED_DEBIT_NOTES_START';
export const GET_VERIFIED_DEBIT_NOTES_SUCCESS = 'GET_VERIFIED_DEBIT_NOTES_SUCCESS';
export const GET_VERIFIED_DEBIT_NOTES_FAIL = 'GET_VERIFIED_DEBIT_NOTES_FAIL';
export const GET_VERIFIED_DEBIT_NOTE_START = 'GET_VERIFIED_DEBIT_NOTE_START';
export const GET_VERIFIED_DEBIT_NOTE_SUCCESS = 'GET_VERIFIED_DEBIT_NOTE_SUCCESS';
export const GET_VERIFIED_DEBIT_NOTE_FAIL = 'GET_VERIFIED_DEBIT_NOTE_FAIL';
export const GET_ORDER_ITEMS_START = 'GET_ORDER_ITEMS_START';
export const GET_ORDER_ITEMS_SUCCESS = 'GET_ORDER_ITEMS_SUCCESS';
export const GET_ORDER_ITEMS_FAIL = 'GET_ORDER_ITEMS_FAIL';
export const GET_DEBIT_NOTE_LINES_START = 'GET_DEBIT_NOTE_LINES_START';
export const GET_DEBIT_NOTE_LINES_SUCCESS = 'GET_DEBIT_NOTE_LINES_SUCCESS';
export const GET_DEBIT_NOTE_LINES_FAIL = 'GET_DEBIT_NOTE_LINES_FAIL';
export const GET_UNVERIFIED_ORDER_PAYMENTS_START = 'GET_UNVERIFIED_ORDER_PAYMENTS_START';
export const GET_UNVERIFIED_ORDER_PAYMENTS_SUCCESS = 'GET_UNVERIFIED_ORDER_PAYMENTS_SUCCESS';
export const GET_UNVERIFIED_ORDER_PAYMENTS_FAIL = 'GET_UNVERIFIED_ORDER_PAYMENTS_FAIL';
export const GET_UNVERIFIED_ORDER_PAYMENT_START = 'GET_UNVERIFIED_ORDER_PAYMENT_START';
export const GET_UNVERIFIED_ORDER_PAYMENT_SUCCESS = 'GET_UNVERIFIED_ORDER_PAYMENT_SUCCESS';
export const GET_UNVERIFIED_ORDER_PAYMENT_FAIL = 'GET_UNVERIFIED_ORDER_PAYMENT_FAIL';
export const GET_CASH_ORDER_PAYMENTS_START = 'GET_CASH_ORDER_PAYMENTS_START';
export const GET_CASH_ORDER_PAYMENTS_SUCCESS = 'GET_CASH_ORDER_PAYMENTS_SUCCESS';
export const GET_CASH_ORDER_PAYMENTS_FAIL = 'GET_CASH_ORDER_PAYMENTS_FAIL';
export const GET_CASH_ORDER_PAYMENT_START = 'GET_CASH_ORDER_PAYMENT_START';
export const GET_CASH_ORDER_PAYMENT_SUCCESS = 'GET_CASH_ORDER_PAYMENT_SUCCESS';
export const GET_CASH_ORDER_PAYMENT_FAIL = 'GET_CASH_ORDER_PAYMENT_FAIL';
export const GET_DEBIT_CARD_ORDER_PAYMENTS_START = 'GET_DEBIT_CARD_ORDER_PAYMENTS_START';
export const GET_DEBIT_CARD_ORDER_PAYMENTS_SUCCESS = 'GET_DEBIT_CARD_ORDER_PAYMENTS_SUCCESS';
export const GET_DEBIT_CARD_ORDER_PAYMENTS_FAIL = 'GET_DEBIT_CARD_ORDER_PAYMENTS_FAIL';
export const GET_DEBIT_CARD_ORDER_PAYMENT_START = 'GET_DEBIT_CARD_ORDER_PAYMENT_START';
export const GET_DEBIT_CARD_ORDER_PAYMENT_SUCCESS = 'GET_DEBIT_CARD_ORDER_PAYMENT_SUCCESS';
export const GET_DEBIT_CARD_ORDER_PAYMENT_FAIL = 'GET_DEBIT_CARD_ORDER_PAYMENT_FAIL';
export const GET_MOBILE_ORDER_PAYMENTS_START = 'GET_MOBILE_ORDER_PAYMENTS_START';
export const GET_MOBILE_ORDER_PAYMENTS_SUCCESS = 'GET_MOBILE_ORDER_PAYMENTS_SUCCESS';
export const GET_MOBILE_ORDER_PAYMENTS_FAIL = 'GET_MOBILE_ORDER_PAYMENTS_FAIL';
export const GET_MOBILE_ORDER_PAYMENT_START = 'GET_MOBILE_ORDER_PAYMENT_START';
export const GET_MOBILE_ORDER_PAYMENT_SUCCESS = 'GET_MOBILE_ORDER_PAYMENT_SUCCESS';
export const GET_MOBILE_ORDER_PAYMENT_FAIL = 'GET_MOBILE_ORDER_PAYMENT_FAIL';
export const GET_TRANSFER_ORDER_PAYMENTS_START = 'GET_TRANSFER_ORDER_PAYMENTS_START';
export const GET_TRANSFER_ORDER_PAYMENTS_SUCCESS = 'GET_TRANSFER_ORDER_PAYMENTS_SUCCESS';
export const GET_TRANSFER_ORDER_PAYMENTS_FAIL = 'GET_TRANSFER_ORDER_PAYMENTS_FAIL';
export const GET_TRANSFER_ORDER_PAYMENT_START = 'GET_TRANSFER_ORDER_PAYMENT_START';
export const GET_TRANSFER_ORDER_PAYMENT_SUCCESS = 'GET_TRANSFER_ORDER_PAYMENT_SUCCESS';
export const GET_TRANSFER_ORDER_PAYMENT_FAIL = 'GET_TRANSFER_ORDER_PAYMENT_FAIL';
export const GET_STOCK_RECEIPTS_START = 'GET_STOCK_RECEIPTS_START';
export const GET_STOCK_RECEIPTS_SUCCESS = 'GET_STOCK_RECEIPTS_SUCCESS';
export const GET_STOCK_RECEIPTS_FAIL = 'GET_STOCK_RECEIPTS_FAIL';
export const GET_STOCK_RECEIPT_START = 'GET_STOCK_RECEIPT_START';
export const GET_STOCK_RECEIPT_SUCCESS = 'GET_STOCK_RECEIPT_SUCCESS';
export const GET_STOCK_RECEIPT_FAIL = 'GET_STOCK_RECEIPT_FAIL';
export const GET_STOCK_RECEIPT_LINES_START = 'GET_STOCK_RECEIPT_LINES_START';
export const GET_STOCK_RECEIPT_LINES_SUCCESS = 'GET_STOCK_RECEIPT_LINES_SUCCESS';
export const GET_STOCK_RECEIPT_LINES_FAIL = 'GET_STOCK_RECEIPT_LINES_FAIL';
export const CREATE_ORDER_START = 'CREATE_ORDER_START';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL';
export const CREATE_DEBIT_NOTE_START = 'CREATE_DEBIT_NOTE_START';
export const CREATE_DEBIT_NOTE_SUCCESS = 'CREATE_DEBIT_NOTE_SUCCESS';
export const CREATE_DEBIT_NOTE_FAIL = 'CREATE_DEBIT_NOTE_FAIL';
export const VERIFY_ORDER_START = 'VERIFY_ORDER_START';
export const VERIFY_ORDER_SUCCESS = 'VERIFY_ORDER_SUCCESS';
export const VERIFY_ORDER_FAIL = 'VERIFY_ORDER_FAIL';
export const PAY_ORDER_START = 'PAY_ORDER_START';
export const PAY_ORDER_SUCCESS = 'PAY_ORDER_SUCCESS';
export const PAY_ORDER_FAIL = 'PAY_ORDER_FAIL';
export const PAY_PARTIALLY_ORDER_START = 'PAY_PARTIALLY_ORDER_START';
export const PAY_PARTIALLY_ORDER_SUCCESS = 'PAY_PARTIALLY_ORDER_SUCCESS';
export const PAY_PARTIALLY_ORDER_FAIL = 'PAY_PARTIALLY_ORDER_FAIL';
export const RECEIVE_STOCK_START = 'RECEIVE_STOCK_START';
export const RECEIVE_STOCK_SUCCESS = 'RECEIVE_STOCK_SUCCESS';
export const RECEIVE_STOCK_FAIL = 'RECEIVE_STOCK_FAIL';
export const RECEIVE_PARTIALLY_STOCK_START = 'RECEIVE_PARTIALLY_STOCK_START';
export const RECEIVE_PARTIALLY_STOCK_SUCCESS = 'RECEIVE_PARTIALLY_STOCK_SUCCESS';
export const RECEIVE_PARTIALLY_STOCK_FAIL = 'RECEIVE_PARTIALLY_STOCK_FAIL';
export const VERIFY_PAYMENT_START = 'VERIFY_PAYMENT_START';
export const VERIFY_PAYMENT_SUCCESS = 'VERIFY_PAYMENT_SUCCESS';
export const VERIFY_PAYMENT_FAIL = 'VERIFY_PAYMENT_FAIL';













