export const CREATE_PROCESS_START = 'CREATE_PROCESS_START';
export const CREATE_PROCESS_SUCCESS = 'CREATE_PROCESS_SUCCESS';
export const CREATE_PROCESS_FAIL = 'CREATE_PROCESS_FAIL';
export const EDIT_PROCESS = 'EDIT_PROCESS';