export const GET_PUBLISHED_EBOOKS_START = 'GET_PUBLISHED_EBOOKS_START';
export const GET_PUBLISHED_EBOOKS_SUCCESS = 'GET_PUBLISHED_EBOOKS_SUCCESS';
export const GET_PUBLISHED_EBOOKS_FAIL = 'GET_PUBLISHED_EBOOKS_FAIL';
export const GET_PUBLISHED_EBOOK_START = 'GET_PUBLISHED_EBOOK_START';
export const GET_PUBLISHED_EBOOK_SUCCESS = 'GET_PUBLISHED_EBOOK_SUCCESS';
export const GET_PUBLISHED_EBOOK_FAIL = 'GET_PUBLISHED_EBOOK_FAIL';
export const EDIT_PUBLISHED_EBOOK = 'EDIT_PUBLISHED_EBOOK';