export const GET_PUBLISHED_HARD_COPIES_START = 'GET_PUBLISHED_HARD_COPIES_START';
export const GET_PUBLISHED_HARD_COPIES_SUCCESS = 'GET_PUBLISHED_HARD_COPIES_SUCCESS';
export const GET_PUBLISHED_HARD_COPIES_FAIL = 'GET_PUBLISHED_HARD_COPIES_FAIL';
export const GET_PUBLISHED_HARD_COPY_START = 'GET_PUBLISHED_HARD_COPY_START';
export const GET_PUBLISHED_HARD_COPY_SUCCESS = 'GET_PUBLISHED_HARD_COPY_SUCCESS';
export const GET_PUBLISHED_HARD_COPY_FAIL = 'GET_PUBLISHED_HARD_COPY_FAIL';
export const EDIT_PUBLISHED_HARD_COPY = 'EDIT_PUBLISHED_HARD_COPY';