export const GET_SERIES_START = 'GET_SERIES_START';
export const GET_SERIES_SUCCESS = 'GET_SERIES_SUCCESS';
export const GET_SERIES_FAIL = 'GET_SERIES_FAIL';
export const CREATE_SERIES_START = 'CREATE_SERIES_START';
export const CREATE_SERIES_SUCCESS = 'CREATE_SERIES_SUCCESS';
export const CREATE_SERIES_FAIL = 'CREATE_SERIES_FAIL';
export const GET_SINGLE_SERIES_START = 'GET_SINGLE_SERIES_START';
export const GET_SINGLE_SERIES_SUCCESS = 'GET_SINGLE_SERIES_SUCCESS';
export const GET_SINGLE_SERIES_FAIL = 'GET_SINGLE_SERIES_FAIL';
export const EDIT_SERIES = 'EDIT_SERIES';
export const GET_SERIES_IMAGES_START = 'GET_SERIES_IMAGES_START';
export const GET_SERIES_IMAGES_SUCCESS = 'GET_SERIES_IMAGES_SUCCESS';
export const GET_SERIES_IMAGES_FAIL = 'GET_SERIES_IMAGES_FAIL';
export const CREATE_SERIES_IMAGE_START = 'CREATE_SERIES_IMAGE_START';
export const CREATE_SERIES_IMAGE_SUCCESS = 'CREATE_SERIES_IMAGE_SUCCESS';
export const CREATE_SERIES_IMAGE_FAIL = 'CREATE_SERIES_IMAGE_FAIL';
export const CREATE_SERIES_COVER_START = 'CREATE_SERIES_COVER_START';
export const CREATE_SERIES_COVER_SUCCESS = 'CREATE_SERIES_COVER_SUCCESS';
export const CREATE_SERIES_COVER_FAIL = 'CREATE_SERIES_COVER_FAIL';


export const GET_PUBLISHED_SERIES_START = 'GET_PUBLISHED_SERIES_START';
export const GET_PUBLISHED_SERIES_SUCCESS = 'GET_PUBLISHED_SERIES_SUCCESS';
export const GET_PUBLISHED_SERIES_FAIL = 'GET_PUBLISHED_SERIES_FAIL';
export const GET_SINGLE_PUBLISHED_SERIES_START = 'GET_SINGLE_PUBLISHED_SERIES_START';
export const GET_SINGLE_PUBLISHED_SERIES_SUCCESS = 'GET_SINGLE_PUBLISHED_SERIES_SUCCESS';
export const GET_SINGLE_PUBLISHED_SERIES_FAIL = 'GET_SINGLE_PUBLISHED_SERIES_FAIL';


export const UNLOCK_SERIES_START = 'UNLOCK_SERIES_START';
export const UNLOCK_SERIES_SUCCESS = 'UNLOCK_SERIES_SUCCESS';
export const UNLOCK_SERIES_FAIL = 'UNLOCK_SERIES_FAIL';










