export const GET_UNLOCKED_CHAPTERS_START = 'GET_UNLOCKED_CHAPTERS_START';
export const GET_UNLOCKED_CHAPTERS_SUCCESS = 'GET_UNLOCKED_CHAPTERS_SUCCESS';
export const GET_UNLOCKED_CHAPTERS_FAIL = 'GET_UNLOCKED_CHAPTERS_FAIL';
export const GET_UNLOCKED_CHAPTER_START = 'GET_UNLOCKED_CHAPTER_START';
export const GET_UNLOCKED_CHAPTER_SUCCESS = 'GET_UNLOCKED_CHAPTER_SUCCESS';
export const GET_UNLOCKED_CHAPTER_FAIL = 'GET_UNLOCKED_CHAPTER_FAIL';