export const GET_UNLOCKED_TOPICS_START = 'GET_UNLOCKED_TOPICS_START';
export const GET_UNLOCKED_TOPICS_SUCCESS = 'GET_UNLOCKED_TOPICS_SUCCESS';
export const GET_UNLOCKED_TOPICS_FAIL = 'GET_UNLOCKED_TOPICS_FAIL';
export const GET_UNLOCKED_TOPIC_START = 'GET_UNLOCKED_TOPIC_START';
export const GET_UNLOCKED_TOPIC_SUCCESS = 'GET_UNLOCKED_TOPIC_SUCCESS';
export const GET_UNLOCKED_TOPIC_FAIL = 'GET_UNLOCKED_TOPIC_FAIL';