export const GET_WAREHOUSES_START = 'GET_WAREHOUSES_START';
export const GET_WAREHOUSES_SUCCESS = 'GET_WAREHOUSES_SUCCESS';
export const GET_WAREHOUSES_FAIL = 'GET_WAREHOUSES_FAIL';
export const GET_WAREHOUSE_START = 'GET_WAREHOUSE_START';
export const GET_WAREHOUSE_SUCCESS = 'GET_WAREHOUSE_SUCCESS';
export const GET_WAREHOUSE_FAIL = 'GET_WAREHOUSE_FAIL';
export const CREATE_WAREHOUSE_START = 'CREATE_WAREHOUSE_START';
export const CREATE_WAREHOUSE_SUCCESS = 'CREATE_WAREHOUSE_SUCCESS';
export const CREATE_WAREHOUSE_FAIL = 'CREATE_WAREHOUSE_FAIL';
export const EDIT_WAREHOUSE = 'EDIT_WAREHOUSE';
export const GET_DELETED_WAREHOUSES_START = 'GET_DELETED_WAREHOUSES_START';
export const GET_DELETED_WAREHOUSES_SUCCESS = 'GET_DELETED_WAREHOUSES_SUCCESS';
export const GET_DELETED_WAREHOUSES_FAIL = 'GET_DELETED_WAREHOUSES_FAIL';
export const GET_DELETED_WAREHOUSE_START = 'GET_DELETED_WAREHOUSE_START';
export const GET_DELETED_WAREHOUSE_SUCCESS = 'GET_DELETED_WAREHOUSE_SUCCESS';
export const GET_DELETED_WAREHOUSE_FAIL = 'GET_DELETED_WAREHOUSE_FAIL';
export const DELETE_WAREHOUSE_START = 'DELETE_WAREHOUSE_START';
export const DELETE_WAREHOUSE_SUCCESS = 'DELETE_WAREHOUSE_SUCCESS';
export const DELETE_WAREHOUSE_FAIL = 'DELETE_WAREHOUSE_FAIL';
export const GET_STORAGE_MEDIAS_START = 'GET_STORAGE_MEDIAS_START'
export const GET_STORAGE_MEDIAS_SUCCESS = 'GET_STORAGE_MEDIAS_SUCCESS'
export const GET_STORAGE_MEDIAS_FAIL = 'GET_STORAGE_MEDIAS_FAIL'
export const CREATE_STORAGE_MEDIA_START = 'CREATE_STORAGE_MEDIA_START'
export const CREATE_STORAGE_MEDIA_SUCCESS = 'CREATE_STORAGE_MEDIA_SUCCESS'
export const CREATE_STORAGE_MEDIA_FAIL = 'CREATE_STORAGE_MEDIA_FAIL'
export const GET_STORAGE_MEDIA_START = 'GET_STORAGE_MEDIA_START'
export const GET_STORAGE_MEDIA_SUCCESS = 'GET_STORAGE_MEDIA_SUCCESS'
export const GET_STORAGE_MEDIA_FAIL = 'GET_STORAGE_MEDIA_FAI'
export const EDIT_STORAGE_MEDIA = 'EDIT_STORAGE_MEDIA'

export const GET_WAREHOUSE_ITEMS_START = 'GET_WAREHOUSE_ITEMS_START';
export const GET_WAREHOUSE_ITEMS_SUCCESS = 'GET_WAREHOUSE_ITEMS_SUCCESS';
export const GET_WAREHOUSE_ITEMS_FAIL = 'GET_WAREHOUSE_ITEMS_FAIL';
export const CREATE_WAREHOUSE_ITEM_START = 'CREATE_WAREHOUSE_ITEM_START';
export const CREATE_WAREHOUSE_ITEM_SUCCESS = 'CREATE_WAREHOUSE_ITEM_SUCCESS';
export const CREATE_WAREHOUSE_ITEM_FAIL = 'CREATE_WAREHOUSE_ITEM_FAIL';



